### ISSUE TITLE
[Bug] lipidlynxx website conversion appears to be broken

### ISSUE THREAD

**Issue by rmflight** [SysMedOs/LipidLynxX#17]
**Describe the bug**
The website conversion service is broken, as of 2021-03-08 at 11:30 EST

**To Reproduce**
1. Go to http://lipidmaps.org/lipidlynxx/converter/
2. Click on "Convert" without changing any settings
3. See error 

    500 Server Error
    OSError: [Errno 24] Too many open files

    File /lipidmaps/python-3.8.4/lib/python3.8/multiprocessing/popen_fork.py, line 68, in _launch
    65.

    66.     def _launch(self, process_obj):
    
    67.         code = 1
    
    68.         parent_r, child_w = os.pipe()
    
    69.         child_r, parent_w = os.pipe()
    
    70.         self.pid = os.fork()
    
    71.         if self.pid == 0:

**Expected behavior**
Expect the default input example to work without changing anything

**Screenshots**
Attached screenshot of starting screen, and of the error output.
 
![Screenshot from 2021-03-08 11-02-19](https://user-images.githubusercontent.com/1509626/110347191-5d612380-7ffe-11eb-8518-13fd8a6689f5.png)

![Screenshot from 2021-03-08 11-02-26](https://user-images.githubusercontent.com/1509626/110347214-6225d780-7ffe-11eb-8289-7ed0914036b5.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome 88.0.4324.96 (Official Build) (64-bit)
 - LipidLynxX Version: whatever is on the website

**Comment by ZhixuNi** [comment]
Hi @rmflight !

Thank you for reporting this issue!
I just had a look, it is now running fine with default settings.
And I used another short query to test as well:
```
PAPE
PLPE
PLPC
```
It is currently working fine.
Please try again and see if you meet the same issue.

Probably there were lots of users at that time. We will have a look on the logs.
Many thanks!
<img width="1920" alt="LipidLynxX_2021-03-08_17-20-40" src="https://user-images.githubusercontent.com/9975812/110349141-ae8b0a80-8032-11eb-95d9-c50aeb98bfee.png">

**Comment by rmflight** [comment]
Great thanks. Just confirmed that it worked.

Maybe it should have another failure mode when there are too many users rather than giving that direct error about too many files open.

**Comment by ZhixuNi** [comment]
Good idea!
We will have a look and try to set a redirection/info page for this kind of errors!
