### ISSUE TITLE
How to read 1Z-alkenylglycerophosphoethanolamines [GP0207] in LipidLynxX [Question]

### ISSUE THREAD

**Issue by JauntyJJS** [SysMedOs/LipidLynxX#22]
Hi,

I wanted to ask how do I correctly convert 1Z-alkenylglycerophosphoethanolamines or LPC-P in [LipidLynxX](http://www.lipidmaps.org/lipidlynxx/converter/).

Initially I thought this is possible because the [BioPAN documentation](https://www.lipidmaps.org/biopan/doc/step1.html) says that it supports the input of LPC-O and LPC-P and to my understanding, BioPAN is using LipidLynxX as a "backend" tools

![image](https://user-images.githubusercontent.com/9066508/173307319-ed417d69-59ee-4220-b0aa-e263589f0996.png)

What I did is to key in the names as follows

![image](https://user-images.githubusercontent.com/9066508/173306860-4a9224f6-2013-4a67-97f3-0db631b4b19b.png)

but it gives me LPC-O instead with one additional double bond

![image](https://user-images.githubusercontent.com/9066508/173307683-504016ac-0a6c-46ea-9f1e-2ad348239439.png)

I tried to convert it from "Bulk" to "Molecular Species"

![image](https://user-images.githubusercontent.com/9066508/173308015-cb7c8c09-cbd9-496c-9679-79f16b5e3d8d.png)

But the system seems to run indefinitely...

![image](https://user-images.githubusercontent.com/9066508/173308626-71d5b857-a1c3-4edd-aa85-07be21179190.png)

Could you help me out in this ?

**Comment by ZhixuNi** [comment]
Hi!
Based on definition of the bulk levels, the P- will be converted to O- with one double bond.
e.g. P-18:0 -> O-18:1
You can have a look of this paper.
https://pubmed.ncbi.nlm.nih.gov/33037133/

The converters generally bring from detailed level e.g. molecular species level like PC(16:0/20:4) PC(P-18:1_0:0) to abstracted level e.g. bulk level like PC(36:4) LPC(O-18:0).

The bulk level to molecular species level ( your second example) is not supported and may case error or unexpected results.

LipidLynxX do not know if PC(O-34:2) is PC(O-16:0_18:2) or PC(P-16:0_18:2) or PC(P-18:0_16:1) ...

Some examples are as below.
You can choose `Shorthand Nomenclature` (without brackets) and `LipidLynxX style` (with brackets).

![SCR-20220627-ija](https://user-images.githubusercontent.com/9975812/175930418-036dc973-1c94-4f28-b5b6-4568e956a0f3.png)

![SCR-20220627-iju](https://user-images.githubusercontent.com/9975812/175930413-e615bd5d-bd33-40f5-9873-17b18e921b61.png)

![SCR-20220627-ik5](https://user-images.githubusercontent.com/9975812/175930409-946f6f73-c012-42dd-a3f3-85d8ad8c166e.png)

![SCR-20220627-ikf](https://user-images.githubusercontent.com/9975812/175930404-6c68f0b9-0755-424d-b367-6d636b8812d2.png)


I hope this is clear for what you asked.

Best,
Ni

**Comment by JauntyJJS** [comment]
Hi,
I have checked the link provided for the bulk definition. Unfortunately, the links provided (if I understood correctly) 
https://lipidmaps.org/resources/tools/bulk_structure_searches_overview.php
http://alex123.info/ALEX123/MS.php

do not seems to work anymore

I have found another link from LipidMaps that seems to provide an explaination of what "bulk" is ?
https://www.lipidmaps.org/databases/comp_db/bulk_structure_searches_documentation

Could you help me verify if this is true ?

It seems that for the LPC(P), to make it work under "Molecular Species Level" settings, I would need to add extra 0:0 like PC(P-16:0_0:0). Does the form LPC(P-16:0_0:0) works as well ?

**Comment by ZhixuNi** [comment]
Hi,
Please stick to the official publication definitions.
You can find an example in Table 4B of this paper:

[https://pubmed.ncbi.nlm.nih.gov/33037133/](https://pubmed.ncbi.nlm.nih.gov/33037133/)

Plasmalogen | PE O-34:2 |   | PE P-16:0/18:1 | PE P-16:0/18:1(9Z)

**ANY OTHER TOOLS/PAGES DO NOT REPLACE THIS OFFICIAL DEFINITION.**

**Please ALWAYS CHECK ONLY this paper for official shorthand notation definitions.**

"It seems that for the LPC(P), to make it work under "Molecular Species Level" settings, I would need to add extra 0:0 like PC(P-16:0_0:0). Does the form LPC(P-16:0_0:0) works as well ?"

Yes, you need to add 0:0 if you know its a lyso species.
The correct way is PC(P-16:0_0:0) in my understanding.

Best,

Ni

**Comment by JauntyJJS** [comment]
I see now. Thank you for the clarification.
